In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
data = pd.read_excel("Sales-Data-Analysis.xlsx")
data.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
1,NaN,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
2,NaN,10453,2022-11-07 00:00:00,Beverages,2.95,745.762712,Online,Gift Card,Pablo Perez,Madrid
3,NaN,10454,2022-11-07 00:00:00,Sides & Other,4.99,200.400802,In-store,Gift Card,Joao Silva,Lisbon
4,NaN,10455,2022-11-08 00:00:00,Burgers,12.99,569.668976,In-store,Credit Card,Walter Muller,Berlin

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255 entries, 0 to 254
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  0 non-null      float64
 1   Unnamed: 1  255 non-null    object
 2   Unnamed: 2  255 non-null    object
 3   Unnamed: 3  255 non-null    object
 4   Unnamed: 4  255 non-null    object
 5   Unnamed: 5  255 non-null    object
 6   Unnamed: 6  255 non-null    object
 7   Unnamed: 7  255 non-null    object
 8   Unnamed: 8  255 non-null    object
 9   Unnamed: 9  255 non-null    object
dtypes: float64(1), object(9)
memory usage: 20.1+ KB

In [15]:
# Drop un named column
data.drop(columns= "Unnamed: 0", inplace=True)

KeyError: "['Unnamed: 0'] not found in axis"

In [17]:
data.loc[0]

Unnamed: 1          Order ID
Unnamed: 2              Date
Unnamed: 3           Product
Unnamed: 4             Price
Unnamed: 5          Quantity
Unnamed: 6     Purchase Type
Unnamed: 7    Payment Method
Unnamed: 8           Manager
Unnamed: 9              City
Name: 0, dtype: object

In [20]:
data.columns = data.loc[0]
data.head()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
0,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
1,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
2,10453,2022-11-07 00:00:00,Beverages,2.95,745.762712,Online,Gift Card,Pablo Perez,Madrid
3,10454,2022-11-07 00:00:00,Sides & Other,4.99,200.400802,In-store,Gift Card,Joao Silva,Lisbon
4,10455,2022-11-08 00:00:00,Burgers,12.99,569.668976,In-store,Credit Card,Walter Muller,Berlin

In [22]:
data.drop(0, inplace=True)

In [24]:
data.head()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
1,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
2,10453,2022-11-07 00:00:00,Beverages,2.95,745.762712,Online,Gift Card,Pablo Perez,Madrid
3,10454,2022-11-07 00:00:00,Sides & Other,4.99,200.400802,In-store,Gift Card,Joao Silva,Lisbon
4,10455,2022-11-08 00:00:00,Burgers,12.99,569.668976,In-store,Credit Card,Walter Muller,Berlin
5,10456,2022-11-08 00:00:00,Chicken Sandwiches,9.95,201.005025,In-store,Credit Card,Walter Muller,Berlin

In [25]:
data.Manager.unique()

array(['Tom      Jackson', '       Pablo Perez', 'Joao    Silva',
       'Walter Muller', 'Remy    Monet', 'Remy Monet',
       '       Remy Monet', 'Remy     Monet', 'Pablo Perez',
       'Pablo   Perez', 'Pablo  Perez', 'Pablo    Perez', 'Joao Silva',
       'Tom Jackson'], dtype=object)

In [27]:
data.Manager.nunique()

14

In [29]:
data["Manager"].str.strip().str.replace(r's+', ' ', regex=True)

1      Tom      Jack on
2           Pablo Perez
3         Joao    Silva
4         Walter Muller
5         Walter Muller
             ...
250       Walter Muller
251       Walter Muller
252       Walter Muller
253       Walter Muller
254       Walter Muller
Name: Manager, Length: 254, dtype: object

In [30]:
data.head(20)

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
1,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
2,10453,2022-11-07 00:00:00,Beverages,2.95,745.762712,Online,Gift Card,Pablo Perez,Madrid
3,10454,2022-11-07 00:00:00,Sides & Other,4.99,200.400802,In-store,Gift Card,Joao Silva,Lisbon
4,10455,2022-11-08 00:00:00,Burgers,12.99,569.668976,In-store,Credit Card,Walter Muller,Berlin
5,10456,2022-11-08 00:00:00,Chicken Sandwiches,9.95,201.005025,In-store,Credit Card,Walter Muller,Berlin
6,10457,2022-11-08 00:00:00,Fries,3.49,573.065903,In-store,Credit Card,Remy Monet,Paris
7,10459,2022-11-08 00:00:00,Sides & Other,4.99,200.400802,In-store,Credit Card,Walter Muller,Berlin
8,10460,2022-11-09 00:00:00,Burgers,12.99,554.272517,In-store,Credit Card,Remy Monet,Paris
9,10461,2022-11-09 00:00:00,Chicken Sandwiches,9.95,201.005025,In-store,Credit Card,Remy Monet,Paris
10,10462,2022-11-09 00:00:00,Fries,3.49,573.065903,In-store,Credit Card,Remy Monet,Paris
11,10463,2022-11-09 00:00:00,Beverages,2.95,677.966102,In-store,Credit Card,Remy Monet,Paris
12,10464,2022-11-09 00:00:00,Sides & Other,4.99,200.400802,In-store,Credit Card,Remy Monet,Paris
13,10465,2022-11-10 00:00:00,Burgers,12.99,554.272517,In-store,Credit Card,Pablo Perez,Madrid
14,10466,2022-11-10 00:00:00,Chicken Sandwiches,9.95,201.005025,In-store,Credit Card,Pablo Perez,Madrid
15,10467,2022-11-10 00:00:00,Fries,3.49,573.065903,In-store,Credit Card,Pablo Perez,Madrid
16,10468,2022-11-10 00:00:00,Beverages,2.95,677.966102,In-store,Credit Card,Pablo Perez,Madrid
17,10470,2022-11-11 00:00:00,Burgers,12.99,554.272517,In-store,Credit Card,Pablo Perez,Madrid
18,10471,2022-11-11 00:00:00,Chicken Sandwiches,9.95,201.005025,In-store,Credit Card,Pablo Perez,Madrid
19,10472,2022-11-11 00:00:00,Fries,3.49,630.372493,In-store,Credit Card,Pablo Perez,Madrid
20,10473,2022-11-11 00:00:00,Beverages,2.95,677.966102,In-store,Credit Card,Pablo Perez,Madrid

In [31]:
data['Manager'].nunique()

14

In [33]:
data.Manager.unique()

array(['Tom      Jackson', '       Pablo Perez', 'Joao    Silva',
       'Walter Muller', 'Remy    Monet', 'Remy Monet',
       '       Remy Monet', 'Remy     Monet', 'Pablo Perez',
       'Pablo   Perez', 'Pablo  Perez', 'Pablo    Perez', 'Joao Silva',
       'Tom Jackson'], dtype=object)

In [35]:
# Removing the duplicate records
data.describe()

C:\Users\gilan\AppData\Local\Temp\ipykernel_19144\4138160892.py:2: FutureWarning: The behavior of value_counts with object-dtype is deprecated. In a future version, this will *not* perform dtype inference on the resulting index. To retain the old behavior, use `result.index = result.index.infer_objects()`
  data.describe()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
count,254,254,254,254.00,254.000000,254,254,254,254
unique,254,53,5,7.00,29.000000,3,3,14,5
top,10452,2022-12-03 00:00:00,Burgers,12.99,200.400802,Online,Credit Card,Tom Jackson,London
freq,1,5,52,52.00,49.000000,107,120,74,75