In [18]:
import pandas as pd
data = pd.read_csv("Police Data Udemy.csv")
data

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,01-02-2005,01:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,1/18/2005,08:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,1/23/2005,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2/20/2005,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,3/14/2005,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65530,12-06-2012,17:54,NaN,F,1987.0,25.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
65531,12-06-2012,22:22,NaN,M,1954.0,58.0,White,Speeding,Speeding,False,NaN,Warning,False,0-15 Min,False
65532,12-06-2012,23:20,NaN,M,1985.0,27.0,Black,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,0-15 Min,False
65533,12-07-2012,00:23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,False
65534,12-07-2012,00:30,NaN,F,1985.0,27.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [19]:
data.isnull().sum()

stop_date                 0
stop_time                 0
country_name          65535
driver_gender          4061
driver_age_raw         4054
driver_age             4307
driver_race            4060
violation_raw          4060
violation              4060
search_conducted          0
search_type           63056
stop_outcome           4060
is_arrested            4060
stop_duration          4060
drugs_related_stop        0
dtype: int64

In [20]:
data.drop(columns="country_name", inplace=True) 
data.drop(columns="search_type", inplace=True)

In [21]:
data

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,01-02-2005,01:55,M,1985.0,20.0,White,Speeding,Speeding,False,Citation,False,0-15 Min,False
1,1/18/2005,08:15,M,1965.0,40.0,White,Speeding,Speeding,False,Citation,False,0-15 Min,False
2,1/23/2005,23:15,M,1972.0,33.0,White,Speeding,Speeding,False,Citation,False,0-15 Min,False
3,2/20/2005,17:15,M,1986.0,19.0,White,Call for Service,Other,False,Arrest Driver,True,16-30 Min,False
4,3/14/2005,10:00,F,1984.0,21.0,White,Speeding,Speeding,False,Citation,False,0-15 Min,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
65530,12-06-2012,17:54,F,1987.0,25.0,White,Speeding,Speeding,False,Citation,False,0-15 Min,False
65531,12-06-2012,22:22,M,1954.0,58.0,White,Speeding,Speeding,False,Warning,False,0-15 Min,False
65532,12-06-2012,23:20,M,1985.0,27.0,Black,Equipment/Inspection Violation,Equipment,False,Citation,False,0-15 Min,False
65533,12-07-2012,00:23,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,False
65534,12-07-2012,00:30,F,1985.0,27.0,White,Speeding,Speeding,False,Citation,False,0-15 Min,False

Question (Based on filtering + Value Counts)

2. For Speeding, were Men or Women stopped more often?

In [22]:
# data[data.violation == "Speeding"]
data.groupby(["driver_gender", "violation_raw"]).size()

driver_gender  violation_raw
F              APB                                    11
               Call for Service                      256
               Equipment/Inspection Violation       1396
               Motorist Assist/Courtesy               40
               Other Traffic Violation              2142
               Registration Violation                632
               Special Detail/Directed Patrol         95
               Speeding                            11686
               Suspicious Person                      11
               Violation of City/Town Ordinance       38
               Warrant                                 3
M              APB                                    40
               Call for Service                      537
               Equipment/Inspection Violation       5120
               Motorist Assist/Courtesy               98
               Other Traffic Violation              9784
               Registration Violation               1611
               Seatbelt Violation                      3
               Special Detail/Directed Patrol       2288
               Speeding                            25517
               Suspicious Person                      27
               Violation of City/Town Ordinance      132
               Warrant                                 7
dtype: int64

In [23]:
data[data.violation == "Speeding"].driver_gender.value_counts()

driver_gender
M    25517
F    11686
Name: count, dtype: int64

Question (Groupby)