In [7]:
import pandas as pd

In [2]:
data = [1,2,3,4,5]
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
# Create a serues from dictionary
data = {"a" : 1, "b" : 3, "c" : 5}
seried_dict = pd.Series(data)
print(seried_dict)

a    1
b    3
c    5
dtype: int64

In [ ]:
data = [10,20,30]
index = ["a", "b", "c"]
pd.Series(data, index = index)

a    10
b    20
c    30
dtype: int64

In [6]:
# Dataframe
# Create from a dictionary of list

data = {
  "Name": ["Krish", "Jhons", "Jack"],
  "Age" : [25,40,50],
  "City" : ["New York", "Texas", "Chicago"]
}

df = pd.DataFrame(data)
print(df)

    Name  Age      City
0  Krish   25  New York
1  Jhons   40     Texas
2   Jack   50   Chicago

In [7]:
import numpy as np
np.array(df)

array([['Krish', 25, 'New York'],
       ['Jhons', 40, 'Texas'],
       ['Jack', 50, 'Chicago']], dtype=object)

In [12]:
# Create a Data Frame from a list of dictionary
data = [
  {"Name" : "Krish","Age" : 32,"City" : "Bangladesh"},
  {"Name" : "Kaysia","Age" : 22,"City" : "New York"},
  {"Name" : "Kustan","Age" : 12,"City" : "Pakistan"},
  {"Name" : "Gilang","Age" : 52,"City" : "Israel"},
]

df = pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age        City
0   Krish   32  Bangladesh
1  Kaysia   22    New York
2  Kustan   12    Pakistan
3  Gilang   52      Israel
<class 'pandas.core.frame.DataFrame'>

In [18]:
# Read a csv file
df = pd.read_csv("transactions.csv")
(df.head())

,Index,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,1,TXN-1001,2026-01-05,Electronics,Wireless Mouse,3,19.99,59.97,North America,Credit Card
1,2,TXN-1002,2026-01-05,Kitchen,Coffee Mug,2,12.50,25.00,North America,PayPal
2,3,TXN-1003,2026-01-06,Electronics,USB-C Cable,5,9.99,49.95,Europe,Credit Card
3,4,TXN-1004,2026-01-06,Stationery,Notebook,10,3.25,32.50,North America,Debit Card
4,5,TXN-1005,2026-01-07,Home Office,Desk Lamp,1,34.00,34.00,Asia,Cash

In [22]:
# Accessing data from dataframe
df.describe()

           Index  Units Sold  Unit Price  Total Revenue
count  15.000000   15.000000   15.000000      15.000000
mean    8.000000    3.133333   41.230000      66.071333
std     4.472136    2.445599   56.435628      49.345642
min     1.000000    1.000000    3.250000      20.250000
25%     4.500000    1.500000   11.245000      34.000000
50%     8.000000    2.000000   19.990000      49.950000
75%    11.500000    4.000000   39.750000      68.970000
max    15.000000   10.000000  199.000000     199.000000

In [32]:
# Handle Missing value
# df.isnull()
df.isnull().any(axis=1)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
dtype: bool

In [9]:
# Handling Missing value with new dataset
df = pd.read_csv('transactions_missing.csv')
df.head()

         Date     Category  Value         Product  Sales         Region
0  2026-01-05  Electronics  19.99  Wireless Mouse    3.0  North America
1  2026-01-05      Kitchen  12.50      Coffee Mug    2.0            NaN
2  2026-01-06  Electronics    NaN     USB-C Cable    5.0         Europe
3  2026-01-06   Stationery   3.25        Notebook    NaN  North America
4  2026-01-07  Home Office  34.00       Desk Lamp    1.0           Asia

In [46]:
# Checking the sum of dataset if there is missing value
df.isnull().sum()

Date        2
Category    0
Value       2
Product     0
Sales       2
Region      2
dtype: int64

In [8]:
# df.head()
df['Sales_fillNA'] = df['Sales'].fillna(df['Sales'].median())
df

NameError: name 'df' is not defined

In [ ]:
# Renaming column
df = df.rename(columns={"Date" : "Sales Date"})

,Sales Date,Category,Value,Product,Sales,Region,Sales_fillNA
0,2026-01-05,Electronics,19.99,Wireless Mouse,3.0,North America,3.000000
1,2026-01-05,Kitchen,12.50,Coffee Mug,2.0,NaN,2.000000
2,2026-01-06,Electronics,NaN,USB-C Cable,5.0,Europe,5.000000
3,2026-01-06,Stationery,3.25,Notebook,NaN,North America,2.000000
4,2026-01-07,Home Office,34.00,Desk Lamp,1.0,Asia,1.000000
5,NaN,Electronics,49.99,Bluetooth Speaker,2.0,North America,2.000000
6,2026-01-08,Sports,15.00,Water Bottle,4.0,NaN,4.000000
7,2026-01-09,Accessories,NaN,Backpack,1.0,North America,1.000000
8,2026-01-10,Electronics,29.99,Keyboard,NaN,Asia,2.000000
9,2026-01-10,Stationery,6.75,Pens (Pack of 12),3.0,Europe,3.000000
10,2026-01-11,Home Office,149.00,Desk Chair,1.0,North America,1.000000
11,NaN,Accessories,12.99,Smartphone Case,6.0,Asia,6.000000
12,2026-01-12,Electronics,199.00,Monitor,1.0,North America,1.000000
13,2026-01-13,Fitness,22.00,Yoga Mat,2.0,Europe,2.000000
14,2026-01-14,Grocery,8.50,Coffee Beans,4.0,North America,4.000000

In [13]:
# Changes data type
df["Value_new"] = df['Value'].fillna(df["Value"].mean()).astype(int)
df.head()

,Date,Category,Value,Product,Sales,Region,Value_new
0,2026-01-05,Electronics,19.99,Wireless Mouse,3.0,North America,19
1,2026-01-05,Kitchen,12.50,Coffee Mug,2.0,NaN,12
2,2026-01-06,Electronics,NaN,USB-C Cable,5.0,Europe,43
3,2026-01-06,Stationery,3.25,Notebook,NaN,North America,3
4,2026-01-07,Home Office,34.00,Desk Lamp,1.0,Asia,34

In [15]:
df['New Value'] = df['Value'].apply(lambda x:x*2)
df.head()

,Date,Category,Value,Product,Sales,Region,Value_new,New Value
0,2026-01-05,Electronics,19.99,Wireless Mouse,3.0,North America,19,39.98
1,2026-01-05,Kitchen,12.50,Coffee Mug,2.0,NaN,12,25.00
2,2026-01-06,Electronics,NaN,USB-C Cable,5.0,Europe,43,NaN
3,2026-01-06,Stationery,3.25,Notebook,NaN,North America,3,6.50
4,2026-01-07,Home Office,34.00,Desk Lamp,1.0,Asia,34,68.00

In [17]:
# Data aggregating and grouping
grouped_mean = df.groupby("Product")['Value'].mean()
grouped_mean.head()

Product
Backpack                NaN
Bluetooth Speaker     49.99
Coffee Beans           8.50
Coffee Mug            12.50
Desk Chair           149.00
Name: Value, dtype: float64